name: Security Scan

on:
  push:
    branches:
      - main
      - master

  pull_request:


jobs:
  dependency-track:
    uses: testAhmal-devsecops-lab/devsecops-orchestrator/.github/workflows/reusable-dtrack.yml@main
    secrets: inherit
    permissions:
      contents: read
